AWSTemplateFormatVersion: "2010-09-09"
Description: serverless function with apiGateway
Resources:
  AdminQueriesCognitoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.handler
      Runtime: nodejs12.x