AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: serverless function with apiGateway
Parameters:
  name:
    Type: String
  templateUrl:
    Type: String
    Default: api/openapi.yml
Resources:
  AdminQueriesCognitoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: !Ref name
      Environment:
        Variables:
          USERPOOL: us-east-1_AFEKQafgQ
      Policies:
        - Statement:
            - Sid: CognitoAccessPolicy
              Effect: Allow
              Action:
                - cognito-idp:ListUsers
              Resource: '*'
  TheApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Ref templateUrl
  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: ApiGatewayExecutionRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - Fn::Sub: ${AdminQueriesCognitoFunction.Arn}